name: Party
main: net.lucynetwork.party.PartyMain
author: Roje
description: 루시 네트워크 파티 플러그인

version: 1.0.0
api-version: 1.13

depend: [ LucyCore ]

commands:
  party:
    aliases: [ 파티 ]
    description: 파티 명령어